# Generated by Django 6.0.4 on 2026-04-27 16:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabins', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=150)),
                ('reservation_type', models.CharField(choices=[('guest_stay', 'Guest Stay'), ('short_stay', 'Short Stay'), ('work_crew', 'Work Crew'), ('farrier', 'Farrier'), ('maintenance_block', 'Maintenance Block'), ('owner_staff', 'Owner / Staff Use'), ('other', 'Other')], default='guest_stay', max_length=40)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('penciled', 'Penciled In'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='penciled', max_length=30)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('check_in_time', models.TimeField(default=datetime.time(15, 0))),
                ('check_out_time', models.TimeField(default=datetime.time(10, 0))),
                ('adult_count', models.PositiveIntegerField(default=0)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('guest_count', models.PositiveIntegerField(default=0, help_text='Optional total guest count. Can be adult + child count or manually adjusted.')),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.household')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_primary_contact', to='clients.client')),
                ('travel_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.travelgroup')),
            ],
            options={
                'ordering': ['arrival_date', 'reservation_name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationCabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_assignments', to='cabins.cabin')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_assignments', to='reservations.reservation')),
            ],
            options={
                'ordering': ['arrival_date', 'cabin__sort_order', 'cabin__name'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['arrival_date'], name='reservation_arrival_e5ded3_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['departure_date'], name='reservation_departu_1fda8d_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_type'], name='reservation_reserva_350522_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['primary_contact'], name='reservation_primary_bf37c0_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['household'], name='reservation_househo_acc02f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['travel_group'], name='reservation_travel__66b74f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationcabin',
            index=models.Index(fields=['arrival_date'], name='reservation_arrival_b0e95a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationcabin',
            index=models.Index(fields=['departure_date'], name='reservation_departu_ab8e05_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationcabin',
            index=models.Index(fields=['cabin'], name='reservation_cabin_i_b3c9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationcabin',
            index=models.Index(fields=['reservation'], name='reservation_reserva_0900a8_idx'),
        ),
    ]
