# Generated by Django 6.0.4 on 2026-04-28 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, help_text='Example: 5\'8" or 68 inches', max_length=50)),
                ('weight', models.CharField(blank=True, help_text='Example: 150 lbs', max_length=50)),
                ('riding_experience', models.CharField(choices=[('unknown', 'Unknown'), ('no_experience', 'No Experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('non_rider', 'Non-Rider')], default='unknown', max_length=30)),
                ('allergies', models.TextField(blank=True)),
                ('food_requests', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_riding', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_guest_records', to='clients.client')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.reservation')),
            ],
            options={
                'ordering': ['client__last_name', 'client__first_name'],
                'indexes': [models.Index(fields=['reservation'], name='reservation_reserva_3132cd_idx'), models.Index(fields=['client'], name='reservation_client__62c7cd_idx'), models.Index(fields=['riding_experience'], name='reservation_riding__5acd86_idx')],
                'constraints': [models.UniqueConstraint(fields=('reservation', 'client'), name='unique_client_per_reservation_guest')],
            },
        ),
    ]
