# Generated by Django 6.0.4 on 2026-04-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
        ('clients', '0001_initial'),
        ('reservations', '0002_reservationguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationguest',
            name='cabin',
            field=models.ForeignKey(blank=True, help_text='Cabin this guest is staying in for this reservation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_guests', to='cabins.cabin'),
        ),
        migrations.AddIndex(
            model_name='reservationguest',
            index=models.Index(fields=['cabin'], name='reservation_cabin_i_2c03f7_idx'),
        ),
    ]
