# Generated by Django 6.0.4 on 2026-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservationguest_cabin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_request_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationguest',
            name='signed_release',
            field=models.BooleanField(default=False),
        ),
    ]
