# Generated by Django 6.0.4 on 2026-08-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_medicalrecord_diagnosis'),
        ('reservations', '0004_reservation_deposit_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationguest',
            name='horse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_guests', to='horses.horse'),
        ),
    ]
