# Generated by Django 6.0.4 on 2026-08-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0005_saddle'),
        ('reservations', '0005_reservationguest_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationguest',
            name='saddle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_guests', to='horses.saddle'),
        ),
    ]
