# Generated by Django 6.0.4 on 2026-09-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservationguest_saddle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name or label for the operating season (e.g. 'Summer 2026', 'Main Season').", max_length=100)),
                ('start_date', models.DateField(help_text='Opening date for the ranch.')),
                ('end_date', models.DateField(help_text='Closing date for the ranch.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this operating season is currently active.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or details about this operating season.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operating Season',
                'verbose_name_plural': 'Operating Seasons',
                'ordering': ['start_date', 'name'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='reservation_start_d_cb0e78_idx'), models.Index(fields=['is_active'], name='reservation_is_acti_2cdcd6_idx')],
            },
        ),
    ]
