# Generated by Django 6.1 on 2026-09-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_operatingseason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationcabin',
            options={'ordering': ['arrival_date', 'cabin__capacity', 'cabin__sort_order', 'cabin__name']},
        ),
    ]
