# Generated by Django 6.0.4 on 2026-10-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservationcabin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='driving_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='flying_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_driving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_flying',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReservationFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure')], default='arrival', max_length=20)),
                ('airport', models.CharField(blank=True, help_text='Airport name or code, e.g. Casper (CPR), Denver (DEN)', max_length=150)),
                ('flight_number', models.CharField(blank=True, help_text='Airline and flight number, e.g. UA 4521', max_length=50)),
                ('flight_date', models.DateField(blank=True, help_text='Flight date', null=True)),
                ('flight_time', models.TimeField(blank=True, help_text='Arrival or departure time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional flight notes (e.g. connections, shuttle requests, passenger names)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='reservations.reservation')),
            ],
            options={
                'ordering': ['flight_type', 'flight_date', 'flight_time', 'created_at'],
                'indexes': [models.Index(fields=['reservation'], name='reservation_reserva_0d9039_idx'), models.Index(fields=['flight_type'], name='reservation_flight__78d1f6_idx'), models.Index(fields=['flight_date'], name='reservation_flight__ca7cee_idx')],
            },
        ),
    ]
