# Generated by Django 6.0.4 on 2026-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_driving_notes_reservation_flying_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationflight',
            options={'ordering': ['airport', 'flight_type', 'flight_date', 'flight_time', 'created_at']},
        ),
        migrations.AddIndex(
            model_name='reservationflight',
            index=models.Index(fields=['airport'], name='reservation_airport_c91106_idx'),
        ),
    ]
