# Generated by Django 6.0.4 on 2026-10-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservationflight_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationguest',
            name='height',
        ),
        migrations.RemoveField(
            model_name='reservationguest',
            name='weight',
        ),
    ]
