# Generated by Django 6.0.4 on 2026-10-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_reservationguest_height_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservationguest',
            name='reservation_riding__5acd86_idx',
        ),
        migrations.RemoveField(
            model_name='reservationguest',
            name='riding_experience',
        ),
    ]
