# Generated by Django 6.0.4 on 2026-07-03 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment', models.TextField(blank=True, help_text='Equipment needed for the project')),
                ('parts', models.TextField(blank=True, help_text='Parts needed for the project')),
                ('proposed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('turned_back', 'Turned Back'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('turned_back', 'Turned Back'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('to_status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('turned_back', 'Turned Back'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project histories',
                'ordering': ['-moved_at'],
            },
        ),
    ]
