# Generated by Django 6.0.4 on 2026-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_other_workers_project_primary_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='other_workers',
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_worker',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='other_workers',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of other workers'),
        ),
    ]
