# Generated by Django 6.0.4 on 2026-07-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
        ('projects', '0003_remove_project_other_workers_and_more'),
        ('vehicles', '0002_maintenancerecord_maintenancestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cabin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cabins.cabin'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_in_ranch_operations',
            field=models.BooleanField(default=False, verbose_name='Show in Ranch Operations'),
        ),
        migrations.AddField(
            model_name='project',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='vehicles.vehicle'),
        ),
    ]
