# Generated by Django 6.0.4 on 2026-08-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0002_cabininventoryitem_cabininventorymaintenancelog'),
        ('projects', '0005_project_assigned_employees_project_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cabin_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cabins.cabininventoryitem'),
        ),
    ]
