# Generated by Django 6.1 on 2026-09-15 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '__first__'),
        ('projects', '0006_project_cabin_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='Assigned contractor, supplier or distributor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contractors.contractor', verbose_name='Distributor / Contractor'),
        ),
    ]
