# Generated by Django 6.0.4 on 2026-07-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('gelding', 'Gelding'), ('mare', 'Mare'), ('stallion', 'Stallion')], default='gelding', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('out_of_service', 'Out of Service'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
