# Generated by Django 6.0.4 on 2026-07-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Legacy medical notes'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(verbose_name='Date of Injury/Sickness')),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('diagnostics', models.TextField(help_text='Diagnostics used')),
                ('required_care', models.TextField(help_text='Required care')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='horses.horse')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCareStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_steps', to='horses.medicalrecord')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
