# Generated by Django 6.0.4 on 2026-07-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_alter_horse_medical_notes_medicalrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcarestep',
            name='status_update',
            field=models.CharField(blank=True, help_text="Update on the horse's condition", max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalcarestep',
            name='description',
            field=models.TextField(help_text='Details of care provided'),
        ),
    ]
