# Generated by Django 6.0.4 on 2026-07-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_medicalcarestep_status_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Sickness/Injury'),
        ),
    ]
