# Generated by Django 6.0.4 on 2026-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_medicalrecord_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saddle_number', models.CharField(max_length=50, unique=True, verbose_name='Saddle Identifier')),
                ('rack_number', models.CharField(blank=True, max_length=50)),
                ('seat_size', models.DecimalField(decimal_places=1, help_text='Seat size in inches (e.g. 14.5)', max_digits=4)),
                ('min_stirrup_length', models.PositiveIntegerField(help_text='In inches')),
                ('max_stirrup_length', models.PositiveIntegerField(help_text='In inches')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('condition', models.PositiveIntegerField(choices=[(1, '1 (Red)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (Green)')], default=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['saddle_number'],
            },
        ),
    ]
