# Generated by Django 6.0.4 on 2026-08-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0005_saddle'),
    ]

    operations = [
        migrations.AddField(
            model_name='saddle',
            name='out_of_service_location',
            field=models.CharField(blank=True, help_text='Location if out of service (e.g. Leather Shop)', max_length=100),
        ),
        migrations.AddField(
            model_name='saddle',
            name='status',
            field=models.CharField(choices=[('in_service', 'In Service'), ('out_of_service', 'Out of Service')], default='in_service', max_length=20),
        ),
        migrations.CreateModel(
            name='SaddleMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='horses.saddle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
