# Generated by Django 6.0.4 on 2026-08-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_saddle_out_of_service_location_saddle_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saddle',
            options={'ordering': ['status', 'rack_number', 'saddle_number']},
        ),
    ]
