# Generated by Django 6.1 on 2026-09-26 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0007_alter_saddle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Pasture notes, acreage, or location description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Column display order on board')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='horse',
            name='pasture',
            field=models.ForeignKey(blank=True, help_text='Current pasture location of the horse', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horses', to='horses.pasture'),
        ),
    ]
