server {
    listen 80 default_server;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /opt/guestranch/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/guestranch/guestranch.sock;
    }
}
