server {
    listen 80;
    server_name your_domain_or_ip;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /opt/guestranch;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/guestranch/guestranch.sock;
    }
}
