# Generated by Django 6.0.4 on 2026-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('suv', 'SUV'), ('van', 'Van'), ('utv', 'UTV/ATV'), ('tractor', 'Tractor'), ('other', 'Other')], default='truck', max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
