# Generated by Django 6.0.4 on 2026-07-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(default='General Maintenance', max_length=255, verbose_name='Issue/Service Type')),
                ('start_date', models.DateField(verbose_name='Date Started')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('diagnostics', models.TextField(help_text='Diagnostics/Inspection results')),
                ('required_maintenance', models.TextField(help_text='Required repairs/service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(help_text='Details of work performed')),
                ('status_update', models.CharField(blank=True, help_text="Update on the vehicle's status", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='vehicles.maintenancerecord')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
