# Generated by Django 6.1 on 2026-09-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business or contractor name', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='Primary sales rep or contact person', max_length=255, verbose_name='Contact Person')),
                ('category', models.CharField(choices=[('distributor', 'Distributor'), ('contractor', 'Contractor'), ('supplier', 'Supplier / Vendor'), ('service', 'Service Provider'), ('other', 'Other')], default='distributor', max_length=50, verbose_name='Type / Category')),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='Postal Code')),
                ('website', models.URLField(blank=True, help_text='e.g. https://example.com')),
                ('notes', models.TextField(blank=True, help_text='Additional information, delivery terms, account numbers, etc.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributor / Contractor',
                'verbose_name_plural': 'Distributors & Contractors',
                'ordering': ['name'],
            },
        ),
    ]
