# Generated by Django 6.0.4 on 2026-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cabin_number', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('bed_configuration', models.CharField(blank=True, help_text='Example: 1 queen, 2 twins, sleeper sofa', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service'), ('inactive', 'Inactive')], default='available', max_length=30)),
                ('housekeeping_status', models.CharField(choices=[('unknown', 'Unknown'), ('clean', 'Clean'), ('dirty', 'Dirty'), ('inspected', 'Inspected'), ('needs_attention', 'Needs Attention')], default='unknown', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order in cabin lists and reservation grids.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='cabins_cabi_name_67f191_idx'), models.Index(fields=['cabin_number'], name='cabins_cabi_cabin_n_0b9eff_idx'), models.Index(fields=['status'], name='cabins_cabi_status_161c97_idx'), models.Index(fields=['housekeeping_status'], name='cabins_cabi_houseke_a7a1e0_idx'), models.Index(fields=['is_active'], name='cabins_cabi_is_acti_db76bb_idx')],
            },
        ),
    ]
