# Generated by Django 6.0.4 on 2026-08-24 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Washing Machine, Refrigerator, King Bed', max_length=150)),
                ('category', models.CharField(choices=[('appliance', 'Appliance'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('fixture', 'Fixture & Plumbing'), ('amenity', 'Amenity & Linens'), ('other', 'Other')], default='appliance', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location_in_cabin', models.CharField(blank=True, help_text='e.g. Laundry Room, Kitchen, Master Bedroom', max_length=100)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken / Needs Repair')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('operational', 'Operational / In Service'), ('maintenance', 'Needs Maintenance'), ('out_of_service', 'Out of Service'), ('replaced', 'Replaced / Disposed')], default='operational', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='cabins.cabin')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CabinInventoryMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='e.g. Filter cleaning, Drum belt repair, Annual inspection', max_length=255)),
                ('performed_by', models.CharField(blank=True, help_text='Staff member, technician or contractor', max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('work_performed', models.TextField(help_text='Details of maintenance/repairs performed')),
                ('status_update', models.CharField(choices=[('operational', 'Operational / In Service'), ('needs_follow_up', 'Needs Follow-up'), ('out_of_service', 'Out of Service')], default='operational', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='cabins.cabininventoryitem')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
