# Generated by Django 6.1 on 2026-09-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0002_cabininventoryitem_cabininventorymaintenancelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabin',
            options={'ordering': ['capacity', 'sort_order', 'name']},
        ),
        migrations.AlterField(
            model_name='cabin',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Secondary display order in cabin lists and reservation grids after capacity.'),
        ),
        migrations.AddIndex(
            model_name='cabin',
            index=models.Index(fields=['capacity'], name='cabins_cabi_capacit_707cce_idx'),
        ),
    ]
