# Generated by Django 6.0.4 on 2026-04-26 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('unknown', 'Unknown'), ('adult', 'Adult'), ('child', 'Child'), ('teen', 'Teen'), ('senior', 'Senior')], default='unknown', max_length=20)),
                ('riding_level', models.CharField(choices=[('unknown', 'Unknown'), ('no_experience', 'No Experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('non_rider', 'Non-Rider')], default='unknown', max_length=30)),
                ('dietary_notes', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='clients_cli_last_na_198e2f_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address_line_1', models.CharField(blank=True, max_length=150)),
                ('address_line_2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_households', to='clients.client')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_households', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('unknown', 'Unknown'), ('self', 'Self'), ('spouse', 'Spouse'), ('partner', 'Partner'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('friend', 'Friend'), ('guardian', 'Guardian'), ('other', 'Other')], default='unknown', max_length=30)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_billing_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='clients.client')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.household')),
            ],
            options={
                'ordering': ['household__name', 'client__last_name', 'client__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('group_type', models.CharField(choices=[('family_reunion', 'Family Reunion'), ('multi_family_trip', 'Multi-Family Trip'), ('wedding', 'Wedding'), ('friend_group', 'Friend Group'), ('corporate_retreat', 'Corporate Retreat'), ('retreat', 'Retreat'), ('other', 'Other')], default='multi_family_trip', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_travel_groups', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary_organizer', 'Primary Organizer'), ('family_unit', 'Family Unit'), ('guest', 'Guest'), ('billing_contact', 'Billing Contact'), ('event_contact', 'Event Contact'), ('other', 'Other')], default='guest', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_group_memberships', to='clients.client')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_group_memberships', to='clients.household')),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.travelgroup')),
            ],
            options={
                'ordering': ['travel_group__name', 'role', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('preference', 'Preference'), ('medical', 'Medical'), ('dietary', 'Dietary'), ('riding', 'Riding'), ('reservation', 'Reservation'), ('follow_up', 'Follow-Up'), ('warning', 'Warning')], default='general', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['note_type'], name='clients_cli_note_ty_f93d1d_idx'), models.Index(fields=['created_at'], name='clients_cli_created_6886e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['name'], name='clients_hou_name_bcd550_idx'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(fields=('household', 'client'), name='unique_client_per_household'),
        ),
        migrations.AddIndex(
            model_name='travelgroup',
            index=models.Index(fields=['name'], name='clients_tra_name_14d647_idx'),
        ),
        migrations.AddIndex(
            model_name='travelgroup',
            index=models.Index(fields=['group_type'], name='clients_tra_group_t_a68b3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='travelgroupmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('household__isnull', False)), models.Q(('client__isnull', False), ('household__isnull', True)), _connector='OR'), name='travel_group_member_household_or_client_not_both'),
        ),
    ]
