# Generated by Django 6.1 on 2026-09-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='years_return',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years returning/visiting Paradise Ranch', null=True, verbose_name='Years Return'),
        ),
        migrations.AddField(
            model_name='household',
            name='years_return',
            field=models.PositiveIntegerField(blank=True, help_text='Default number of years returning/visiting Paradise Ranch for this household', null=True, verbose_name='Years Return'),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='years_return',
            field=models.PositiveIntegerField(blank=True, help_text='Default number of years returning/visiting Paradise Ranch for this travel group', null=True, verbose_name='Years Return'),
        ),
    ]
