# Generated by Django 6.1 on 2026-09-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_years_return_household_years_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.CharField(blank=True, help_text='e.g. 5\'8" or 68 inches', max_length=50, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_rider',
            field=models.BooleanField(default=True, help_text='Whether this client participates in horseback riding activities.', verbose_name='Is Rider'),
        ),
        migrations.AddField(
            model_name='client',
            name='rider_notes',
            field=models.TextField(blank=True, help_text='Horse preferences, saddle requirements, riding experience details, or comfort notes.', verbose_name='Riding & Horse Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='saddle_preference',
            field=models.CharField(blank=True, help_text='e.g. 15" Western, Youth, 16" standard', max_length=100, verbose_name='Saddle Preference'),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 150 lbs', max_length=50, verbose_name='Weight'),
        ),
    ]
