# Generated by Django 6.0.4 on 2026-10-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years if date of birth is unknown or approximate.', null=True, verbose_name='Age'),
        ),
    ]
