# Generated by Django 6.0.4 on 2026-08-02 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('end_of_contract', 'End of Contract'), ('left_early', 'Left Early')], default='active', max_length=20)),
                ('status_reason', models.TextField(blank=True, help_text='Reason for termination, end of contract, or leaving early')),
                ('performance_notes', models.TextField(blank=True)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('job_offered', 'Job Offered'), ('follow_up', 'Follow-up Required'), ('not_recommended', 'Not Recommended'), ('promotion_recommended', 'Recommended for Promotion'), ('promotion_follow_up', 'Promotion Follow-up')], max_length=30)),
                ('is_interviewing', models.BooleanField(default=False, verbose_name='Interviewing')),
                ('offered_position', models.CharField(blank=True, help_text='Position offered if job offered', max_length=255)),
                ('follow_up_reason', models.TextField(blank=True, help_text='Reason why follow-up is required')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
