# Generated by Django 6.1 on 2026-09-15 22:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(help_text='Unique stock number or SKU (e.g. STK-101, B-042)', max_length=50, unique=True, verbose_name='Stock Number')),
                ('description', models.CharField(help_text="Item description / name (e.g. Maker's Mark Bourbon 750ml, Coors Banquet 12oz)", max_length=255, verbose_name='Description')),
                ('category', models.CharField(choices=[('liquor', 'Spirits & Liquor'), ('beer', 'Beer & Cider'), ('wine', 'Wine & Champagne'), ('mixers', 'Mixers & Non-Alcoholic'), ('supplies', 'Bar Supplies & Garnishes'), ('other', 'Other')], default='liquor', max_length=50, verbose_name='Category')),
                ('on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current number of units / singles in stock', max_digits=10, verbose_name='On Hand')),
                ('minimum_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum threshold quantity before reordering', max_digits=10, verbose_name='Minimum On Hand')),
                ('single_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price paid per single bottle/unit', max_digits=10, verbose_name='Single Price')),
                ('case_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price paid per case pack', max_digits=10, verbose_name='Case Price')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Standard menu / retail price (we don't track actual charge for well/call/top)", max_digits=10, verbose_name='Sale Price')),
                ('singles_per_case', models.PositiveIntegerField(default=1, help_text='Number of single bottles / cans / units in one case pack', verbose_name='Singles per Case')),
                ('location', models.CharField(blank=True, default='Main Bar', help_text='e.g. Main Bar, Back Storage, Cooler, Wine Cellar', max_length=100, verbose_name='Storage Location')),
                ('unit_type', models.CharField(blank=True, default='Bottle', help_text='e.g. Bottle, Can, Keg, Pack, Box', max_length=50, verbose_name='Unit Type')),
                ('notes', models.TextField(blank=True, help_text='Special ordering instructions, vintage notes, seasonal item...', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, help_text='Beverage distributor or supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_items', to='contractors.contractor', verbose_name='Distributor')),
            ],
            options={
                'verbose_name': 'Bar Inventory Item',
                'verbose_name_plural': 'Bar Inventory Items',
                'ordering': ['category', 'description', 'stock_number'],
            },
        ),
    ]
