# Generated by Django 6.1 on 2026-09-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Whisky, Rum, Dark Rum, Bourbon, Tequila, Vodka, IPA', max_length=100, unique=True, verbose_name='Tag / Type Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bar Item Tag',
                'verbose_name_plural': 'Bar Item Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='barinventoryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tag-style types (e.g. Whisky, Rum, Dark Rum, Bourbon, Tequila, Vodka, IPA)', related_name='bar_items', to='bar.baritemtag', verbose_name='Types / Tags'),
        ),
    ]
