# Generated by Django 6.1 on 2026-09-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_baritemtag_barinventoryitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='barinventoryitem',
            name='beverage_class',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('well', 'Well'), ('top', 'Top Shelf'), ('domestic', 'Domestic'), ('import', 'Import')], help_text='Class tier if sold by class: Call, Well, Top, Domestic, or Import', max_length=20, null=True, verbose_name='Beverage Class / Tier'),
        ),
        migrations.AddField(
            model_name='barinventoryitem',
            name='pricing_method',
            field=models.CharField(choices=[('by_price', 'By Price'), ('by_class', 'By Class')], default='by_class', help_text='How alcohol is sold: by price or by class', max_length=20, verbose_name='Pricing Method'),
        ),
    ]
