# Generated by Django 6.1 on 2026-09-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_barinventoryitem_beverage_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barinventoryitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='barinventoryitem',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Single tag-style type (e.g. Whisky, Rum, Dark Rum, Bourbon, Tequila, Vodka, IPA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_items', to='bar.baritemtag', verbose_name='Type / Tag'),
        ),
    ]
