# Generated by Django 6.0.4 on 2026-07-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RanchPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_ranch', 'Can view ranch operations'), ('edit_ranch', 'Can edit ranch operations')],
                'managed': False,
            },
        ),
    ]
